name: Go
  cd go-app
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build ./...

    - name: Lint
      run: golangci-lint run

    - name: Test
      run: go test -v ./...

      - name: GolangCI-Lint
       run: golangci-lint run

      